"""Ensemble / stacking layer for NRL match prediction.

Combines Elo, logistic-regression, and XGBoost probabilities via either:
- ``weighted``: simplex-constrained weights learned by minimising log-loss
  (scipy.optimize SLSQP over the base-model probability matrix).
- ``stacked``: a small logistic-regression meta-learner fit on the base-model
  probability columns as features.

In both modes the ensemble layer is trained on **held-out** probability
estimates generated by base models that have not seen those matches —
no future-leak. The standard training protocol is:
  1. Fit base models on the first 75 % of history (chronological).
  2. Generate probabilities for the remaining 25 % using those base models.
  3. Fit the ensemble layer on those probabilities.
  4. Re-fit the base models on the full 100 % for inference.

Kill switch: if the ensemble's cross-validated log-loss does not beat the
best single base model by ``_KILL_THRESHOLD`` (0.5 pp), the ensemble is
disabled and ``predict_ensemble`` returns the best base model's probability.
"""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass
from typing import Literal

import numpy as np
from scipy.optimize import minimize
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import TimeSeriesSplit

EnsembleMode = Literal["weighted", "stacked"]

_KILL_THRESHOLD = 0.005  # 0.5 percentage-point improvement required
_MIN_ROWS = 20  # minimum ensemble-training rows for CV to be meaningful


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _logloss(y: np.ndarray, p: np.ndarray) -> float:
    p = np.clip(p, 1e-9, 1.0 - 1e-9)
    return float(-np.mean(y * np.log(p) + (1.0 - y) * np.log(1.0 - p)))


def _fit_weights(p: np.ndarray, y: np.ndarray) -> np.ndarray:
    """Optimise log-loss over the unit simplex (weights ≥ 0, sum = 1)."""
    n_models = p.shape[1]
    w0 = np.ones(n_models) / n_models

    def objective(w: np.ndarray) -> float:
        return _logloss(y, p @ w)

    result = minimize(
        objective,
        w0,
        method="SLSQP",
        bounds=[(0.0, 1.0)] * n_models,
        constraints={"type": "eq", "fun": lambda w: w.sum() - 1.0},
        options={"ftol": 1e-9, "maxiter": 500},
    )
    return result.x if result.success else w0


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class EnsembleResult:
    """Fitted ensemble layer returned by ``fit_ensemble``."""

    mode: EnsembleMode
    base_names: tuple[str, ...]
    weights: np.ndarray  # shape (n_models,)
    intercept: float  # meta-learner intercept; 0.0 for "weighted"
    kill_switch: bool  # True → ensemble disabled; use best base model instead
    best_base_idx: int  # index of the best single model by CV log-loss


def fit_ensemble(
    probs: np.ndarray,
    y: np.ndarray,
    base_names: Sequence[str],
    mode: EnsembleMode = "stacked",
    *,
    kill_switch_threshold: float = _KILL_THRESHOLD,
    n_cv_splits: int = 3,
    random_state: int = 0,
) -> EnsembleResult:
    """Fit an ensemble layer from base-model probability columns.

    Parameters
    ----------
    probs:
        Shape ``(n_samples, n_models)``, chronologically ordered.  Each column
        is the home-win probability output of one base model.
    y:
        Shape ``(n_samples,)``, integer labels (1 = home win, 0 = away win).
    base_names:
        Ordered identifiers for the base models (for provenance only).
    mode:
        ``"weighted"`` — simplex-constrained blend; ``"stacked"`` — logistic
        meta-learner.
    kill_switch_threshold:
        Required log-loss improvement over the best single base model.
    n_cv_splits:
        Number of ``TimeSeriesSplit`` folds used for the kill-switch CV.
    random_state:
        Passed to sklearn's ``LogisticRegression`` for reproducibility.
    """
    n, n_models = probs.shape
    assert len(base_names) == n_models, "base_names length must match probs columns"

    # ------------------------------------------------------------------ #
    # Time-series CV to assess kill switch
    # ------------------------------------------------------------------ #
    actual_splits = min(n_cv_splits, max(2, n // _MIN_ROWS))
    tscv = TimeSeriesSplit(n_splits=actual_splits)

    ens_cv_losses: list[float] = []
    base_cv_losses: list[list[float]] = [[] for _ in range(n_models)]

    for train_idx, val_idx in tscv.split(probs):
        p_tr, y_tr = probs[train_idx], y[train_idx]
        p_val, y_val = probs[val_idx], y[val_idx]

        if len(np.unique(y_tr)) < 2 or len(val_idx) == 0:
            continue

        if mode == "weighted":
            w = _fit_weights(p_tr, y_tr)
            ens_p = np.clip(p_val @ w, 1e-9, 1.0 - 1e-9)
        else:
            lr = LogisticRegression(C=1.0, max_iter=1000, random_state=random_state)
            lr.fit(p_tr, y_tr)
            raw = p_val @ lr.coef_[0] + lr.intercept_[0]
            ens_p = 1.0 / (1.0 + np.exp(-raw))

        ens_cv_losses.append(_logloss(y_val, ens_p))
        for i in range(n_models):
            base_cv_losses[i].append(_logloss(y_val, probs[val_idx, i]))

    # ------------------------------------------------------------------ #
    # Kill-switch decision
    # ------------------------------------------------------------------ #
    per_model_mean = [float(np.mean(bl)) if bl else float("inf") for bl in base_cv_losses]
    best_base_idx = int(np.argmin(per_model_mean))
    best_base_loss = per_model_mean[best_base_idx]
    mean_ens_loss = float(np.mean(ens_cv_losses)) if ens_cv_losses else float("inf")
    kill_switch = (best_base_loss - mean_ens_loss) < kill_switch_threshold

    # ------------------------------------------------------------------ #
    # Final fit on full training data
    # ------------------------------------------------------------------ #
    if mode == "weighted":
        weights = _fit_weights(probs, y)
        intercept = 0.0
    else:
        lr_final = LogisticRegression(C=1.0, max_iter=1000, random_state=random_state)
        lr_final.fit(probs, y)
        weights = lr_final.coef_[0].copy()
        intercept = float(lr_final.intercept_[0])

    return EnsembleResult(
        mode=mode,
        base_names=tuple(base_names),
        weights=weights,
        intercept=intercept,
        kill_switch=kill_switch,
        best_base_idx=best_base_idx,
    )


def predict_ensemble(probs: np.ndarray, result: EnsembleResult) -> np.ndarray:
    """Apply a fitted ensemble to base-model probability columns.

    Parameters
    ----------
    probs:
        Shape ``(n_samples, n_models)`` — same column order as used in
        ``fit_ensemble``.
    result:
        Fitted ``EnsembleResult`` from ``fit_ensemble``.

    Returns
    -------
    np.ndarray
        Shape ``(n_samples,)`` — blended home-win probabilities in [0, 1].
    """
    if result.kill_switch:
        return probs[:, result.best_base_idx]

    if result.mode == "weighted":
        return np.clip(probs @ result.weights, 0.0, 1.0)

    # stacked: logistic meta-learner
    raw = probs @ result.weights + result.intercept
    return 1.0 / (1.0 + np.exp(-raw))
